# Use an official Python runtime as a parent image
FROM python:3.10.18-bookworm

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  build-essential \
  libpq-dev \
  gcc && \
  rm -rf /var/lib/apt/lists/*

# Install Python dependencies
# This path is relative to the build context (project root)
COPY requirements.txt .
RUN pip install --upgrade pip && \
  pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code from the build context
# This will copy the entire project, including the 'docker' directory
COPY . .
