services:
  database:
    image: postgres:16-bookworm
    env_file:
      - ./.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:8.0.2-bookworm
    restart: always

  backend:
    build:
      context: ..
      dockerfile: docker/dockerfile
    # The docker-compose.yml command overrides the Dockerfile CMD
    command: fastapi run --host 0.0.0.0 --port 8000 src/main.py
    env_file:
      - ./.env.prod
    depends_on:
      - database
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    restart: always

  celery_worker:
    build:
      context: ..
      dockerfile: docker/dockerfile
    command: celery -A src.core.celery.celery_app worker --loglevel=info
    env_file:
      - ./.env.prod
    depends_on:
      - backend
      - redis
    restart: always

  celery_beat:
    build:
      context: ..
      dockerfile: docker/dockerfile
    command: celery -A src.core.celery.celery_app beat --loglevel=info
    env_file:
      - ./.env.prod
    depends_on:
      - backend
      - redis
    restart: always

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
